"""Compile shared code-native pixel art into tiny native drawing spans.
Run with --check in CI; edit Assets/Pet/Puke.json, not generated files.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

def generated():
    art = json.loads((ROOT / 'Assets/Pet/Puke.json').read_text(encoding='utf-8'))
    colors = list(art['palette'])
    cs = ['// Generated by scripts/Generate-pet-art.py. Edit Assets/Pet/Puke.json.', 'using System.Collections.Generic;', 'namespace Relay;', 'internal readonly record struct PetPixel(int X, int Y, int Width, int Color);', 'internal static class PetArtwork', '{', '    internal static readonly string[] Palette = [' + ', '.join(json.dumps(art['palette'][c]) for c in colors) + '];', '    internal static readonly Dictionary<string, PetPixel[]> Layers = new()', '    {']
    sw = ['// Generated by scripts/Generate-pet-art.py. Edit Assets/Pet/Puke.json.', 'struct PetPixel { let x: Int; let y: Int; let width: Int; let color: Int }', 'enum PetArtwork {', '    static let palette = [' + ', '.join(json.dumps(art['palette'][c]) for c in colors) + ']', '    static let layers: [String: [PetPixel]] = [']
    for name, layer in art['layers'].items():
        spans = []
        for y, row in enumerate(layer['rows']):
            x = 0
            while x < len(row):
                color = row[x]; end = x + 1
                while end < len(row) and row[end] == color: end += 1
                if color != '.':
                    assert color in colors, (name, color)
                    px, py = layer['x'] + x, layer['y'] + y
                    assert px >= 0 and px + end-x <= art['width'] and 0 <= py < art['height'], (name, px, py)
                    spans.append((px, py, end-x, colors.index(color)))
                x = end
        cs += ['        ["' + name + '"] = [', '            ' + ', '.join('new(%d, %d, %d, %d)' % span for span in spans), '        ],']
        sw += ['        "' + name + '": [', '            ' + ', '.join('PetPixel(x: %d, y: %d, width: %d, color: %d)' % span for span in spans), '        ],']
    cs += ['    };', '    internal static readonly (int X, int Y)[][] Gait = [']
    sw += ['    ]', '    static let gait: [[(x: Int, y: Int)]] = [']
    for frame in art['gait']:
        assert len(frame) == 4 and all(len(p) == 2 and all(-1 <= v <= 1 for v in p) for p in frame)
        row = ', '.join('(%d, %d)' % tuple(foot) for foot in frame)
        cs += ['        [' + row + '],']; sw += ['        [' + row + '],']
    cs += ['    ];', '    internal static readonly Dictionary<string, string[]> Wardrobe = new()', '    {']
    sw += ['    ]', '    static let wardrobe: [String: [String]] = [']
    for pose, layers in art['wardrobe'].items():
        assert len(layers) == 2 and all(name in art['layers'] for name in layers)
        names = ', '.join(json.dumps(name) for name in layers)
        cs += [f'        ["{pose}"] = [{names}],']
        sw += [f'        "{pose}": [{names}],']
    cs += ['    };', '}']; sw += ['    ]', '}']
    sayings = json.loads((ROOT / 'Assets/Pet/Quotes.json').read_text(encoding='utf-8'))['quotes']
    quotes = [q['text'] for q in sayings]
    authors = [q['author'] for q in sayings]
    owners = [a.lower() if a in ['Puke', 'Roof', 'Rock'] else 'all' for a in authors]
    assert all(q['author'] in ['Puke', 'Roof', 'Rock'] or q.get('source', '').startswith('https://') for q in sayings)
    assert len(quotes) > 1 and len(set(quotes)) == len(quotes) and all(isinstance(q, str) and 0 < len(q) <= 90 for q in quotes)
    cs += ['// Companion sayings and attributed quotations from Assets/Pet/Quotes.json.', 'internal static class PetSayings', '{',
           '    internal static readonly string[] Quotes = [' + ', '.join(json.dumps(q) for q in quotes) + '];',
           '    internal static readonly string[] Authors = [' + ', '.join(json.dumps(a) for a in authors) + '];',
           '    internal static readonly string[] Owners = [' + ', '.join(json.dumps(o) for o in owners) + '];', '}']
    sw += ['// Companion sayings and attributed quotations from Assets/Pet/Quotes.json.', 'enum PetSayings {',
           '    static let quotes = [' + ', '.join(json.dumps(q) for q in quotes) + ']',
           '    static let authors = [' + ', '.join(json.dumps(a) for a in authors) + ']',
           '    static let owners = [' + ', '.join(json.dumps(o) for o in owners) + ']', '}']
    return {'windows/Sources/Relay/PetArtwork.cs': '\n'.join(line.rstrip() for line in cs)+'\n', 'macos/Sources/RelayMac/PetArtwork.swift': '\n'.join(line.rstrip() for line in sw)+'\n'}

def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    for name, source in generated().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != source:
                raise SystemExit(f'{name} is stale. Run python scripts/Generate-pet-art.py')
        else: path.write_text(source, encoding='utf-8')
    print('PASS: shared companion pixel artwork is current' if args.check else 'Generated native companion artwork')

if __name__ == '__main__': main()
